### ISSUE TITLE
Int overflow for SCO ID in scoInfo() method

### ISSUE THREAD

**Issue by Gribanov** [brunogasparetto/AdobeConnectClient#1]
Hi Bruno.
Thank you for your library, it is great.
However when I started to play with it I found that it converts sco ids to integer values using `intval()` function. My client has sco id 3327764235 which is getting converted to -967203061 on windows and php 7.2.6 for example. 
Code in question is located here `Commands/ScoInfo.php:28`. Maybe other methods have similar problems.
Unfortunately I'm not very skilled with github to provide pull-request, so I'm just creating this issue.

Thank you for your hard work on this library.

**Comment by brunogasparetto** [comment]
Hi.

I will fix this in this weekend.

Thanks!
