### ISSUE TITLE
ErrorException filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated 

### ISSUE THREAD

**Issue by faniuta** [brunogasparetto/AdobeConnectClient#2]
hi 
 i have this exeption when create a new class (php v7.3)
ErrorException
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated 
in 
vendor/brunogasparetto/adobe-connect-client/src/Connection/Curl/Connection.php:54 

`$connection = new Connection($this->base_url);
        $client =  new Client($connection);`

**Comment by brunogasparetto** [comment]
Hi.

Thanks for the issue.

I removed the deprecated flag.
